# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import helper_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=helper_app.models.temporary_image_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
