# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0003_auto_20171122_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryimage',
            name='relative_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
