# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import helper_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0002_temporaryimage_relative_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryimage',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='temporaryimage',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='temporaryimage',
            name='img',
            field=models.ImageField(height_field='height', upload_to=helper_app.models.temporary_image_directory_path, width_field='width'),
        ),
    ]
