# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 14:19
from __future__ import unicode_literals

from django.db import migrations
from user.models import User


POPULATE_USERNAME = False
def populate_username(apps, schema_editor):
    if not POPULATE_USERNAME:
        return

    users = User.objects.all()
    for user in users:
        user.username = user.email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_username'),
    ]

    operations = [
        migrations.RunPython(populate_username),
    ]
