# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove nullable in username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='users/picture/anonymous.jpg', upload_to=user.models.picture_directory_path),
        ),
    ]
